import React, { useState } from "react";
import Head from "next/head";
import useSWR from "swr";
import {
  DataGrid,
  GridToolbarQuickFilter,
  GridToolbarFilterButton,
  GridToolbarContainer,
} from "@mui/x-data-grid";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import SignupModal from "../components/SignupModal";

function QuickSearchToolbar() {
  return (
    <GridToolbarContainer>
      <GridToolbarQuickFilter
        placeholder="Search by song title or artist..."
        sx={{ width: "350px" }}
      />
      <GridToolbarFilterButton />
    </GridToolbarContainer>
  );
}

const columns = [
  {
    field: "title",
    headerName: "Song Name",
    minWidth: 400,
  },
  {
    field: "artist",
    headerName: "Artist",
    minWidth: 400,
  },
  {
    field: "diskNumber",
    headerName: "Disk Number",
    minWidth: 200,
  },
];

export default function Home() {
  const [song, setSong] = useState<Record<string, string> | undefined>();
  const { data, error } = useSWR("/api/songs", () => {
    return fetch("/api/songs").then((res) => res.json());
  });

  return (
    <>
      <Head>
        <title>Garage Karaoke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Typography variant="h3">Garage Karaoke - Song List</Typography>
        {song && <SignupModal {...song} onClose={setSong} />}
        <Box sx={{ height: "80vh", width: "100%" }}>
          <DataGrid
            loading={!data}
            getRowId={(row) => row._id}
            pagination
            onRowClick={({ row, id }) => {
              setSong({ ...row, id });
            }}
            columns={columns}
            rows={data || []}
            components={{ Toolbar: QuickSearchToolbar }}
          />
        </Box>
      </Box>
    </>
  );
}
