import Head from "next/head";
import useSWR from "swr";
import { DataGrid, GridToolbarQuickFilter } from "@mui/x-data-grid";
import Box from "@mui/material/Box";
import Container from "../components/Container";
import Heading from "../components/Heading";

function QuickSearchToolbar() {
  return (
    <Box
      sx={{
        p: 1,
        pb: 0,
        alignSelf: "flex-end",
        width: "100%",
        display: "flex",
        minWidth: 400,
      }}
    >
      <GridToolbarQuickFilter
        placeholder="Search by song title or artist..."
        sx={{ width: "350px" }}
      />
    </Box>
  );
}

const columns = [
  {
    field: "title",
    headerName: "Song Name",
    minWidth: 400,
  },
  {
    field: "artist",
    headerName: "Artist",
    minWidth: 400,
  },
  {
    field: "diskNumber",
    headerName: "Disk Number",
    minWidth: 200,
  },
];

export default function Home() {
  const { data, error } = useSWR("/api/songs", () => {
    return fetch("/api/songs").then((res) => res.json());
  });

  return (
    <>
      <Head>
        <title>Garage Karaoke</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container direction="column">
        <Heading>Garage Karaoke - Song List</Heading>
        <Box sx={{ height: "80vh", width: "100%" }}>
          <DataGrid
            loading={!data}
            getRowId={(row) => row._id}
            pagination
            columns={columns}
            rows={data || []}
            components={{ Toolbar: QuickSearchToolbar }}
          />
        </Box>
      </Container>
    </>
  );
}
